services:
  - type: web
    name: venta-farmacia
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: |
      php /var/www/html/venta-gatito/artisan migrate --force && \
      apache2-foreground
